"""Shared fixtures: a small committed slice of the real CFTC parquet files.

The suite never fetches. Every frame here comes from tests/fixtures/*.parquet,
which is a ~0.5 MB subset of data/ regenerated by `python -m tests.fixtures.build`
-- read that module's docstring before changing a selection, because each code in
the slice is there to make one specific awkward case true (a contract re-basing,
a nonzero-net market-week, a null trader count beside a nonzero position, two
markets sharing one name, a pre-2002 non-weekly cadence).

tests/ is a package, so pytest imports this file as `tests.conftest` -- a test
module that wants the constants below imports them from that path, not from a bare
`conftest`.

Three rules for using these fixtures:

- The frames are REAL published figures, so assertions must use the tolerances in
  lib/cftc_spec rather than exact equality. Exact equality is the bug this suite
  exists to prevent regressing.
- Per-test fixtures hand out copies. The parquet read is session-scoped because
  it is the only slow thing here, but panels routinely do
  `df["report_date"] = pd.to_datetime(...)`, so a shared frame would leak dtype
  changes between tests exactly the way st.cache_resource leaks them between
  page loads (see lib/cache.py).
- Nothing here writes to data/. `tmp_data_dir` points lib.store at a tmp_path for
  the write tests; `fixture_data_dir` points it at the committed slice for read
  tests. Neither ever touches the repo's own parquet files.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import pytest

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"
REPO_ROOT = FIXTURE_DIR.parent.parent

# The repo is not installed as a package, so put its root on the path before any
# test module does `from lib import ...`. conftest is imported first, which is
# the only reason this works here rather than in a pytest.ini.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

#: The four CFTC families in the slice, one per cohort taxonomy plus the
#: supplemental. futopt is deliberately absent: it is the same parser and the
#: same invariants on the same shape, so it would double the fixture and test
#: nothing new. What it would test -- that fut and futopt do not reconcile --
#: needs no data, only spec.is_combined.
CFTC_SOURCES: tuple[str, ...] = (
    "cftc_tff_fut",
    "cftc_legacy_fut",
    "cftc_disagg_fut",
    "cftc_supp_cit",
)

#: Every source present in the slice, so `fixture_data_dir` can stand in for data/.
FIXTURE_SOURCES: tuple[str, ...] = CFTC_SOURCES + ("openrouter_pricing", "umich_sca")

#: Codes whose presence specific tests depend on. Named here so a fixture
#: rebuild that drops one fails with this list rather than with an empty frame.
NASDAQ_CONSOLIDATED = "20974+"  # cftc_tff_fut: the 2023-05-02 unit break
NASDAQ_EMINI = "209742"  # a SUPERSEDED_BY leg of 20974+
NASDAQ_BIG = "209741"  # legacy: shares a name with 209742 on 1999-06-22
BITCOIN = "133741"  # cftc_tff_fut: null traders_long beside a nonzero long
GOLD = "088691"  # legacy from 1986: pre-2002 non-weekly cadence
WHEAT_SRW = "001602"  # cftc_supp_cit: worst rounding, no conc columns

#: The date CFTC re-based its Consolidated equity indices. Open interest in
#: 20974+ goes 49,531 -> 255,954 here with no change in positioning.
UNIT_BREAK_DATE = "2023-05-02"


def _read(source_id: str) -> pd.DataFrame:
    path = FIXTURE_DIR / f"{source_id}.parquet"
    if not path.exists():
        raise pytest.UsageError(
            f"missing test fixture {path}. Regenerate the slice with "
            "`python -m tests.fixtures.build` (it reads data/, not the network)."
        )
    return pd.read_parquet(path)


@pytest.fixture(scope="session")
def fixture_dir() -> Path:
    return FIXTURE_DIR


@pytest.fixture(scope="session")
def _session_frames() -> dict[str, pd.DataFrame]:
    """Read every fixture parquet once. Do not depend on this directly -- it is
    shared mutable state; take `cftc_frames` or a named frame instead."""
    return {sid: _read(sid) for sid in FIXTURE_SOURCES}


@pytest.fixture
def cftc_frames(_session_frames) -> dict[str, pd.DataFrame]:
    """source_id -> tidy frame, for the four CFTC families. Fresh copies."""
    return {sid: _session_frames[sid].copy() for sid in CFTC_SOURCES}


@pytest.fixture(params=CFTC_SOURCES)
def cftc_frame(request, _session_frames) -> tuple[str, pd.DataFrame]:
    """(source_id, frame), parametrised over all four families.

    Invariant tests take this so a family that breaks is named in the test id
    rather than hidden inside a loop that stops at the first failure.
    """
    return request.param, _session_frames[request.param].copy()


@pytest.fixture
def tff_fut(_session_frames) -> pd.DataFrame:
    """Financial futures: the unit break, the nonzero nets, the negative residual."""
    return _session_frames["cftc_tff_fut"].copy()


@pytest.fixture
def legacy_fut(_session_frames) -> pd.DataFrame:
    """1986-2026 gold plus the 1999 NASDAQ name collision. comm has no spread."""
    return _session_frames["cftc_legacy_fut"].copy()


@pytest.fixture
def disagg_fut(_session_frames) -> pd.DataFrame:
    """Commodities. The control case: its residual is exactly zero on every row."""
    return _session_frames["cftc_disagg_fut"].copy()


@pytest.fixture
def supp_cit(_session_frames) -> pd.DataFrame:
    """Supplemental. Rounds worst, no concentration columns, three cohorts unspread."""
    return _session_frames["cftc_supp_cit"].copy()


@pytest.fixture
def openrouter_pricing(_session_frames) -> pd.DataFrame:
    return _session_frames["openrouter_pricing"].copy()


@pytest.fixture
def nasdaq_consolidated(tff_fut) -> pd.DataFrame:
    """20974+ across the 2023-05-02 re-basing, date-sorted. 846 reports.

    The series a percentile must NOT be computed over in one piece: levels
    before and after the break differ by 5.17x for units, not positioning.
    """
    df = tff_fut[tff_fut["market_code"].astype(str) == NASDAQ_CONSOLIDATED]
    assert not df.empty, f"{NASDAQ_CONSOLIDATED} missing from the tff fixture"
    return df.sort_values(["report_date", "cohort"]).reset_index(drop=True)


@pytest.fixture
def gold_legacy(legacy_fut) -> pd.DataFrame:
    """088691 from 1986-01-15, date-sorted. 1,931 reports, 200 of the 1,930 gaps
    are not 7 days -- the series that breaks "one row back is one week"."""
    df = legacy_fut[legacy_fut["market_code"].astype(str) == GOLD]
    assert not df.empty, f"{GOLD} missing from the legacy fixture"
    return df.sort_values(["report_date", "cohort"]).reset_index(drop=True)


def _market_weeks(df: pd.DataFrame) -> pd.DataFrame:
    """Collapse cohort rows to one row per (market_code, report_date).

    `first` rather than `sum` on open_interest, traders_total and the
    concentration columns: those are market-week level and are repeated
    identically on every cohort row, so summing them multiplies by the cohort
    count. That mistake is silent -- it produces a plausible number 3-5x too big.

    Sums use min_count=1 so an all-null spread column (legacy comm, disagg
    prod_merc, nonrept everywhere) stays distinguishable from a genuine zero;
    callers that want the accounting identity fill it with 0 explicitly.
    """
    g = df.groupby(["market_code", "report_date"], observed=True)
    out = pd.DataFrame(
        {
            "long_sum": g["long"].sum(min_count=1),
            "short_sum": g["short"].sum(min_count=1),
            "spread_sum": g["spread"].sum(min_count=1),
            "open_interest": g["open_interest"].first(),
            "cohorts": g["cohort"].nunique(),
        }
    )
    return out.reset_index()


@pytest.fixture
def market_weeks():
    """The market-week collapse, as a callable, so both test modules share one
    definition of what "one market-week" means."""
    return _market_weeks


@pytest.fixture
def fixture_data_dir(monkeypatch) -> Path:
    """Point lib.store (and therefore lib.cache) at the committed slice.

    Use this for anything that goes through store.read / cache.read / a panel,
    so a test reads the 0.5 MB slice instead of the 115 MB real dataset -- and so
    a test can never depend on a market that happens to be in data/ today.
    """
    from lib import store

    monkeypatch.setattr(store, "DATA_DIR", FIXTURE_DIR)
    return FIXTURE_DIR


@pytest.fixture
def tmp_data_dir(tmp_path, monkeypatch) -> Path:
    """Point lib.store at an empty tmp dir. Mandatory for any test that writes:
    store.upsert MERGES into whatever is already at DATA_DIR, so a write test
    aimed at the real data/ would silently rewrite a committed 29 MB file."""
    from lib import store

    target = tmp_path / "data"
    target.mkdir()
    monkeypatch.setattr(store, "DATA_DIR", target)
    return target
